[metadata]
org = "gofunky.fun"
maintainer = "matfax (mat@fax.fyi)"
description = "Azure Kubernetes Service Autoscaling Service"

[settings]
kubeContext = "kube-system"
serviceAccount = "tiller"
storageBackend = "configMap"

[apps]
    # akscale will be deployed using the Tiller in the kube-system namespace
    [apps.akscale]
    namespace = "kube-system" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "." # changing the chart name means delete and recreate this release
    version = "0.1.0" # chart version
    ### Optional values below
    name = "akscale" # should be unique across all apps which are managed by the same Tiller
    valuesFile = "" # leaving it empty uses the default chart values
    tillerNamespace = "kube-system" # which Tiller to use to deploy this release
    purge = true # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    protected = false
    priority= -2
    wait = true
    [apps.akscale.set.azure] # values to override values from values.yaml with values from env vars or directly entered
         clientID = "$CLIENT_ID"
         clientSecret = "$CLIENT_SECRET"
         resourceGroup = "$AKS_RESOURCE_GROUP"
         subscriptionID = "$SUBSCRIPTION_ID"
         tenantID = "$AZURE_TENANT_ID"
         clusterName = "$AKS_CLUSTER_NAME"
         nodeResourceGroup = "$NODE_RESOURCE_GROUP"
