apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-azure
  namespace: kube-system
  labels:
    app: {{ template "autoscaler.name" . }}
    chart: {{ template "autoscaler.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ClientID: {{ .Values.azure.clientID | b64enc | quote }}
  ClientSecret: {{ .Values.azure.clientSecret | b64enc | quote }}
  ResourceGroup: {{ .Values.azure.resourceGroup | b64enc | quote }}
  SubscriptionID: {{ .Values.azure.subscriptionID | b64enc | quote }}
  TenantID: {{ .Values.azure.tenantID | b64enc | quote }}
  VMType: QUtTCg==
  ClusterName: {{ .Values.azure.clusterName | b64enc | quote }}
  NodeResourceGroup: {{ .Values.azure.nodeResourceGroup | b64enc | quote }}
---
